version: '3.8'
services:
 backend:
  build:
   context: ../../material-applications/example-backend/
   dockerfile: Dockerfile
  command: ['./server']
  environment:
   PORT: 8080
   REQUEST_ORIGIN: http://localhost:5000
  ports:
   - 8080:8080
 frontend:
  build:
   context: ../../material-applications/example-frontend/
   dockerfile: Dockerfile 
  command: ['serve', '-s', '-l', '5000', 'build']
  environment:
   PORT: 5000
  ports:
   - 5000:5000

