FROM node:16-alpine

WORKDIR /app

RUN adduser -D myuser

COPY package*.json ./

RUN chown -R myuser:myuser /app

USER myuser

RUN npm install

COPY --chown=myuser:myuser . .

RUN npm run build

USER root

RUN npm install -g serve

USER myuser

EXPOSE 5000

CMD ["serve", "-s", "-l", "5000", "build"]